### ISSUE TITLE
【每日计划】 2021-12-14

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#260]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by jp-liu** [comment]
![image](https://user-images.githubusercontent.com/79979500/145908668-e93e7b9b-4a85-4067-a154-ffb709b8db83.png)

**Comment by CsongL** [comment]
![image](https://user-images.githubusercontent.com/30070610/145908922-be420243-c8eb-4446-abe1-358684fcce8c.png)

**Comment by fengjinlong** [comment]
<img width="979" alt="image" src="https://user-images.githubusercontent.com/19486973/145912319-00be27b2-d8ae-4b72-a33c-5f5f9e1ce335.png">

**Comment by lixudong96** [comment]
## TODO
- [ ] 出去玩
- [ ] vue-magic-issue2
- [ ] vue-magic-issue3

**Comment by bigfatDone** [comment]
![image](https://user-images.githubusercontent.com/41776522/145914407-d2604b42-bb10-4c62-8f9c-53979b9f2cea.png)

**Comment by shuzong** [comment]
![image](https://user-images.githubusercontent.com/95478370/145915402-adc3803c-966a-49f1-9572-21df00d80438.png)

**Comment by luhaifeng666** [comment]
## 工作
- [ ] 官网替换白皮书下载地址
- [ ] 数据对接
## 学习
- [ ] 刷一道算法，并输出到git
- [ ] 刷两篇技术帖
- [ ] 完善cli-create-tool 工具
## 生活
- [ ] 铲屎

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/145916134-a0332563-e928-4561-8154-15f09ffd8432.png)

**Comment by cherishing** [comment]
![image](https://user-images.githubusercontent.com/8589964/145916397-a8a5ebbd-a595-4142-99f7-bb29812426d5.png)

**Comment by xiaoxiayan** [comment]
![image](https://user-images.githubusercontent.com/42376534/145916860-9805082b-3d6b-4c59-8daf-5364358094e3.png)

**Comment by amebyte** [comment]
mini-vue学习

**Comment by Enoch-q** [comment]
## 学习
  - [ ] 总结整理this
  - [ ] 总结整理笔记
  - [ ] minivue学习
 ## 工作
  - [ ] 表格封装--抽离配置文件
  - [ ] 将列表生成通过plop优化

**Comment by WalkerChan2019** [comment]
![image](https://user-images.githubusercontent.com/53211980/145920326-b5f399ee-06bd-4ad0-b618-e9469a477074.png)

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/145921173-33bad2a0-65fd-4fd8-b7cf-a6781da3cd01.png)

**Comment by cuixiaorui** [comment]
![image](https://user-images.githubusercontent.com/12064746/145923701-e26c234e-20b2-4a36-a73f-1d3a89d02090.png)

**Comment by JingYuZhou123** [comment]
![image](https://user-images.githubusercontent.com/40521805/145933634-4a003665-113a-423a-8972-c28161022ecd.png)
