### ISSUE TITLE
【每日计划】 2021-12-29

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#283]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by CsongL** [comment]
![image](https://user-images.githubusercontent.com/30070610/147615993-c0f544bd-5967-4ec8-ae27-1fb54ae2dfac.png)

**Comment by CsongL** [comment]
![image](https://user-images.githubusercontent.com/30070610/147616006-132f1533-9232-4f6e-8765-9781d1f066cb.png)

**Comment by Reinharclt** [comment]
![image](https://user-images.githubusercontent.com/35991053/147617288-7a550ce0-a0c9-4fd4-aa43-099adccbdea9.png)

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/147617342-c5ca4612-1379-4529-ba75-e35906958e04.png)

**Comment by fengjinlong** [comment]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/19486973/147617357-69bf331d-86dc-4ce5-8977-13b4fbdff882.png">

**Comment by orzsoso** [comment]
react-jsx
补觉
学习

**Comment by jp-liu** [comment]
![image](https://user-images.githubusercontent.com/79979500/147618250-1c619457-cc76-473d-800f-e7b46743c2ac.png)

**Comment by likui628** [comment]
读文档
  - [ ] [Composition API](https://v3.vuejs.org/api/composition-api.html)
  - [ ] [Single File Components](https://v3.vuejs.org/api/sfc-spec.html)
 
看视频
  - [ ] [Vue 3 Script Setup, The Future Of Vue? Tutorial And Setup](https://youtu.be/9uSNKIXH_AI)
  - [ ] [Vue 3: Reactivity Made Easy (ref, reactive, toRefs... oh my!)](https://youtu.be/sAj6tdVS2cA)

共读issues
  - [ ] [ToRef types Error #5121 #5](https://github.com/cuixiaorui/vue-magic/issues/5)

**Comment by bigfatDone** [comment]
![image](https://user-images.githubusercontent.com/41776522/147618330-becee2df-839f-473f-a671-a45b0272a9e5.png)

**Comment by luhaifeng666** [comment]
## 工作
- [ ] 筛选组件文档补充
- [ ] 菜单组件支持click-outside
## 学习
- [ ] 练习一道算法，并输出到git
- [ ] 刷两篇技术帖
- [ ] 昨日未完成的mini-vue输出，接着写完
## 生活
- [ ] 铲屎

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [ ] 《CSS 新世界》
- [ ] 红宝书
- [ ] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [ ] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by Enochzzz** [comment]
## 学习
- [ ] es6 promise，generator，async相关
- [ ] minivue

## 工作
- [ ] 低代码方案调研
      

---- 来自vscode插件 "Study Plan"

**Comment by Jsmond2016** [comment]
![image](https://user-images.githubusercontent.com/25282180/147620322-de83b8ed-c716-4e2d-9037-fe9eecbba793.png)


[plan-1229](https://jsmond2016.github.io/study-everyday/record/12/1229.html)

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/147620538-225675ed-2e2a-49b2-98c1-ea4b6838dd4c.png)

**Comment by threedayAAAAA** [comment]
# 工作 
- 摸鱼看完gitbook js核心技术专栏
# 生活
- 锻炼30m

**Comment by JingYuZhou123** [comment]
![image](https://user-images.githubusercontent.com/40521805/147620681-8804be32-8286-4bc7-ba70-8f4e7283a640.png)

**Comment by wty9sky** [comment]
# 每日计划
- [ ] 学习mini-vue第3、4节
- [ ] go学习面向对象与面向接口的内容
- [ ] react学习

**Comment by lwt09** [comment]
![image](https://user-images.githubusercontent.com/55039185/147622887-543aee93-d1c8-48b8-8d7b-091e6899183b.png)

**Comment by cuixiaorui** [comment]
## 重要的事
- [ ] [[ToRef types Error 5121]]
- [ ] [[vue3 中的 PropType 都做了什么]]


## 学习
- [ ] 自然拼读 Kk #英语/自然拼读 
- [ ] [[学习高手]]
- [ ] [[零基础学好英语语法]]


## 生活
- [ ] 收拾鞋架

**Comment by liuliuwab** [comment]
1. 工作：看公司代码 搞懂一个组件 看哈业务逻辑
2. 其他任务：1-2道算法题  发布一个文章

**Comment by Irving2020** [comment]
Important

1：完成工作任务
2：观看算法视频
3：计划明年任务

General

1：English Daliy

Low

1：leetCode算法题

**Comment by lixudong96** [comment]
## TODO
- [ ] mini-vue
- [ ] 后台项目搭建
- [ ] typingclub

**Comment by shuzong** [comment]
![image](https://user-images.githubusercontent.com/95478370/147633886-cdc07b73-4a55-4db6-9d41-fd41aaf076ba.png)

**Comment by JackenJ** [comment]
![image](https://user-images.githubusercontent.com/77328954/147634954-8ce49833-df65-4d23-9a50-ec562e53a689.png)

**Comment by JackenJ** [comment]
![image](https://user-images.githubusercontent.com/77328954/147635002-06523f0a-202b-4c01-8fe1-1fd623e296db.png)

**Comment by zhenyuWang** [comment]
### 昨天完成
数据结构-并查集
[掘金](https://juejin.cn/post/7047014200962449445) [B站](https://www.bilibili.com/video/BV1ra4116755?spm_id_from=333.999.0.0)
leetcode-990-等式方程的可满足性
[掘金](https://juejin.cn/post/7047020570453475336) [B站](https://www.bilibili.com/video/BV1sY411p7Dm?spm_id_from=333.999.0.0)
面试题-symbol 有什么用处？
### 今天要做
面试题-NaN 是什么，用 typeof 会输出什么？
leetcode-684-冗余连接
leetcode-1319-连通网络的操作次数
输出掘金 B站

**Comment by chressYu** [comment]
![image](https://user-images.githubusercontent.com/91681351/147641830-1c5c0f96-630f-4a4e-9f0c-442dbb734bb5.png)

**Comment by lingcha** [comment]
![image](https://user-images.githubusercontent.com/29124405/147671606-4677376b-fa82-44ec-b0b9-d1c1163145ef.png)
