### ISSUE TITLE
【每日计划】 2021-12-31

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#287]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by JingYuZhou123** [comment]
![8e432015337e508b082ef1454238927](https://user-images.githubusercontent.com/40521805/147771229-ac9b945d-fb03-4a54-86af-2b7600742e58.png)

**Comment by Reinharclt** [comment]
![image](https://user-images.githubusercontent.com/35991053/147796122-01682f66-cc21-49e8-9166-650773cf750d.png)

**Comment by fengjinlong** [comment]
<img width="468" alt="image" src="https://user-images.githubusercontent.com/19486973/147797177-91443a11-365f-4a21-a317-59a35adfe737.png">

**Comment by threedayAAAAA** [comment]
## 工作
- 搭建项目文档平台，将路由骨架上库
- 预研下 doc转md的可行性

## 学习
- minivue 1h
- 研究下油猴脚本

## 生活
- 陪女朋友跨年

**Comment by luhaifeng666** [comment]
## 工作
- [ ] table组件优化继续
## 学习
- [ ] 练习算法，并输出到git（断了两天了。。）
- [ ] 刷两篇技术帖
## 生活
- [ ] 铲屎

**Comment by xiaoxiayan** [comment]
![image](https://user-images.githubusercontent.com/42376534/147797901-ac1e580c-8212-4cb2-8ca5-e33e45e903d4.png)

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/147797900-9cc2d433-1f3e-4fe5-a24f-9d22219f8887.png)

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [ ] 《CSS 新世界》
- [ ] 红宝书
- [ ] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [ ] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by lixudong96** [comment]
## TODO
- [ ] js执行原理
- [ ] 作用域链
- [ ] 闭包
- [ ] mini-vue

**Comment by Jsmond2016** [comment]
![image](https://user-images.githubusercontent.com/25282180/147798207-443713a2-44ed-4b27-a2cf-b73f6aba090f.png)

[plan-1231](https://jsmond2016.github.io/study-everyday/record/12/1231.html)

**Comment by likui628** [comment]
看视频
  - [ ] [Vue.js Advanced Component Composition Patterns](https://youtu.be/SrKCiv15_NU)
  - [ ] [Vue 3: Working With Components And $ATTRS ! $listeners is Deprecated! What WILL WE DO? // VUE 3 TUT](https://youtu.be/Rv4tKV_cqYU)
  - [ ] [Build and Deploy a Fully Responsive Modern UI/UX Website in React JS](https://youtu.be/LMagNcngvcU)

共读issues
  - [ ] [ToRef types Error #5121 #5](https://github.com/cuixiaorui/vue-magic/issues/5)

写代码
  - [ ] `Build and Deploy a Fully Responsive Modern UI/UX Website in React JS` vue3 实现

**Comment by bigfatDone** [comment]
![image](https://user-images.githubusercontent.com/41776522/147798348-3ae4b0b1-7c65-4dde-abd4-e4234b05441c.png)

**Comment by cherishing** [comment]
![image](https://user-images.githubusercontent.com/8589964/147798368-02e45904-8fbe-4d8c-960b-fcaceed19fc4.png)

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/147799020-50a0426f-ba86-43f8-b3ac-92f59a1816f2.png)

**Comment by wty9sky** [comment]
# 每日计划
- [ ] 学习mini-vue第3、4节
- [ ] go学习面向对象与面向接口的内容
- [ ] react学习

**Comment by shuzong** [comment]
![image](https://user-images.githubusercontent.com/95478370/147799321-c0cd498b-47dd-4773-8de1-60ac6f48aea4.png)

**Comment by Enochzzz** [comment]
## 学习
- [ ] es6 两小时学习+笔记
- [ ] 红宝书两小时学习+笔记
- [ ] minivue

## 工作
- [ ] 低代码方案调研
- [ ] 测试
      

---- 来自vscode插件 "Study Plan"

**Comment by Irving2020** [comment]
Important
1：计划明年任务
2：观看算法视频

General

1：English Daliy
2：🏀 1h

Low

1：leetCode算法题

**Comment by huangd-d** [comment]
1. 思否、掘金 看技术文
2. 观看 mini-vue 06

**Comment by zhenyuWang** [comment]
### 昨天完成
leetcode-128-最长连续序列
[掘金](https://juejin.cn/post/7047669835567726629) [B站](https://www.bilibili.com/video/BV1cD4y1w7dz?spm_id_from=333.999.0.0)
面试题-如何判断一个对象是不是空对象？
### 今天要做
leetcode-947-移除最多的同行或同列石头
leetcode-1202-交换字符串中的元素
输出掘金 B站
面试题-如何判断数组类型?

**Comment by cuixiaorui** [comment]
## 重要的事
- [x] 买小鹅通
- [x] 沟通服务的想法
- [ ] [[mini-vue]]


## 学习
- [ ] 自然拼读 Kk #英语/自然拼读 
- [ ] 自然拼读 Ll #英语/自然拼读 
- [ ] [[学习高手]]
- [ ] [[零基础学好英语语法]]


## 生活

**Comment by jp-liu** [comment]
![image](https://user-images.githubusercontent.com/79979500/147803369-917ae112-981d-4fe4-a28c-331ac9f70ee0.png)

**Comment by qc-z** [comment]
mini-vue 实现组件props逻辑

**Comment by amebyte** [comment]
mini-vue学习

**Comment by liruiheng1** [comment]
`学习vim库的操作指令`
