### ISSUE TITLE
【每日计划】 2022-01-10

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#305]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by luhaifeng666** [comment]
## 学习
- [x] 练习一道算法，并输出到git
- [x] 刷两篇技术帖子
## 生活
- [x] 铲屎

**Comment by Reinharclt** [comment]
![image](https://user-images.githubusercontent.com/35991053/148707479-2dbdff3f-49a0-4b4c-98ab-7e2e5c2083f1.png)

**Comment by jp-liu** [comment]
![image](https://user-images.githubusercontent.com/79979500/148708077-29bf02be-c769-4649-a798-68150945d63d.png)

**Comment by liyicheng94** [comment]
![image](https://user-images.githubusercontent.com/74058775/148708125-cc8258ba-1c65-4d03-8db4-4d8a8e2e7db5.png)

**Comment by WalkerChan2019** [comment]
### 昨日完成
1、算法题：https://github.com/WalkerChan2019/followxia_studybook/blob/main/2022-Jan/0109/bracket.js
2、预习图和树：广度优先搜索和深度优先搜索

### 今日计划：
工作 + 一道算法题

**Comment by ghost** [comment]
#### Preview
- [ ] Vuex


#### Task
- [ ] 电商后台管理主页布局
- [ ] 电商后台管理用户管理

**Comment by bigfatDone** [comment]
![image](https://user-images.githubusercontent.com/41776522/148708494-ae6445db-8e57-47b4-bfa9-c3c47ff39bf0.png)

**Comment by icodeish** [comment]
#### 重要的事
- [ ] leetcode每日一题
- [ ] 摸鱼

**Comment by sevdot** [comment]
重要的事情

- [ ] 完成工作任务

自我提升

- [ ] 阅读《三十岁，一切刚刚开始》

**Comment by wty9sky** [comment]
# 2022-1-10 计划清单

## 重要的事
- [ ] 制定年度目标和计划


## 学习
- [ ] 学习mini-vue，git提交项目
- [ ] 继续写koa短网址的文章
- [ ] leetcode一道算法题


## 生活
- [x] 喝腊八粥

**Comment by REABLE-l** [comment]
## 每日计划 - 2022-01-10
- [x] 英语高级语法
- [x] mini-vue
- [x] 约妹子下午茶
- [x] 打拳半小时
- [x] 《野外生存指南》

**Comment by littlewhitehhh** [comment]
![image](https://user-images.githubusercontent.com/71918265/148709317-33da030f-abdd-4bfb-bdf8-579beb1cc572.png)

**Comment by Rainer-Yu** [comment]
## 今日 TODO
- [x] 点播课列表页
- [x] 套餐课列表页
- [x] 列表 `END` 组件

## 学习
- [x] 学习 `Proxy`
- [ ] 研究画漂亮的示例图

## 生活
- [x] 搞点腊八粥

**Comment by yekezz** [comment]
## 学习
- [ ] es6 两小时学习
- [ ] minivue
- [ ] 智能合约相关资料了解

## 工作
- [ ] bug修复
- [ ] 测试
      

---- 来自vscode插件 "Study Plan"

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [x] 《CSS 新世界》
- [x] 红宝书
- [x] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [x] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by Vixcity** [comment]
# 2022-01-10日计划

2022-01-10日计划创建时间：2022-01-10 星期一  09:02
2022-01-10日计划创建人：Vixcity

## 重要的事
- [x] 别忘记给每日计划添加到目录里面去

## 学习
- [ ] 学习TS
- [x] 收集好用的轮子资料

## 生活
- [ ] 手账
- [ ] 1000天

## 今日工作内容
给公司的电脑安装clover
希望能够今日份摸鱼😂
小程序

**Comment by CsongL** [comment]
![image](https://user-images.githubusercontent.com/30070610/148709704-21680cf8-e008-41bf-8f07-2e8e86860f5a.png)

**Comment by Elben9** [comment]
- [ ] leetcode * 1
- [ ] ts类型体操 * 1
- [ ] mini-vue

**Comment by myltx** [comment]
![image](https://user-images.githubusercontent.com/29727848/148710000-688b9e21-b41e-494b-bc61-aa04d26248f2.png)

**Comment by cherishing** [comment]
![image](https://user-images.githubusercontent.com/8589964/148710059-4b23cb6d-cb5e-4e63-8081-2d0a1ae32267.png)

**Comment by Artsmp** [comment]
# 学习
- [x] 学习高程4的函数一章
- [x] 继续学习函数式编程完成笔记记录

# 工作
- [x] 封装 uni-app 请求模块，完成 token 逻辑

# 日常
- [x] 每日护肤
- [x] 12:00 睡觉
- [ ] 7:00 起床：未完成
- [x] 半小时看书
- [x] 午睡半小时

**Comment by lwt09** [comment]
![image](https://user-images.githubusercontent.com/55039185/148710428-d14a21c7-afb7-46f4-a74f-571d4796e942.png)

**Comment by cggcbb** [comment]
### 【每日计划】 2022-01-10

#### 重要的事

- [ ] bug 修改.

#### 学习

- [x] 学习 Pinia

#### 其他

- [x] 骑车半小时
 
 ###### 更新时间：2022-01-10 13:55:01

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/148710678-6539556e-8445-4ab6-9a56-58afbfff4ed9.png)

**Comment by 1078269653** [comment]
## 生活
  - [x] 护肤
  - [x] 运动40分钟
## 学习
  - [x] 学习javascript书籍一小时
  - [x] 观看web前端教学视频三小时
  - [x] 阅读喜欢书籍一小时

**Comment by Jsmond2016** [comment]
![image](https://user-images.githubusercontent.com/25282180/148711368-a7fd06ed-bfb6-4608-9ef7-9a5cbe216e10.png)

[0110](https://jsmond2016.github.io/study-everyday/record-2022/01/0110.html)

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/148711668-508cd1df-cfa4-49d9-84b7-b6d100be47c2.png)

**Comment by cuixiaorui** [comment]
## 重要的事
- 研发 [[mini-vue]] 
	- 探索编译的时机 [[mini-vue 编译模块#runtime 调用 compiler 的时机]]
	- [x] 实现 compiler function mode 
	- [x] template 编译成 render 的流程跑通
- [x] 录制共读 issue



## 学习
- [x] [[学习高手]]
- [x] [[零基础学好英语语法]]
- [ ] 自然拼读复习到 Pp #英语/自然拼读 

## 生活

**Comment by fengjinlong** [comment]
### 重要的事情

- [ ] 1

### 学习的事情

- [ ] 

### 生活的事情

- [ ]

**Comment by action-hong** [comment]
## 工作

- [x] 产品上线测试准备

## 学习

- [ ] leetcode每日一题
- [x] `webpack`相关知识点

**Comment by fengjinlong** [comment]
#### 重要的事情 🍎

- [x] minivue

#### 学习的事情 🧑‍💻

- [x] ts
- [x] typing

#### 工地的事情 💤

- [x] ai bug

#### 生活的事情 🍒

- [x] 休息

**Comment by Blacktuna1** [comment]
#### 学习上
- [ ] 标日第二课
- [ ] 力扣两道题
- [ ] 背20个单词
- [ ] 大作业题目
#### 生活上
- [ ] 社交
- [ ] 泡杯咖啡
- [ ] 早一点起
- [ ] 早一点睡

**Comment by lingcha** [comment]
## 重要
- [ ] 阅读了不起的nodejs，尝试应用今天阅读的部分重构自己写的node应用
	- [ ] static中间件
	- [ ] query中间件
	- [ ] logger中间件
	- [ ] bodyparser中间件
	- [ ] cookie
	- [ ] session
	- [ ] redis.cookie
	- [ ] methodoverride中间件
	- [ ] basicauth中间件
- [ ] 阅读TypeScript官网的ObjectTypes
	- [ ] Property Modifiers
	- [ ] Optional Properties
	- [ ] readonly Properties
	- [ ] Index Signatures
	- [ ] Extending Types
	- [ ] Intersection Types

### 练习
- [ ] type-challenges练习3道，完成简单部分
	- [ ] Push
	- [ ] Unshift
	- [ ] Parameters

## 可选项
运用bootstrap5开发组件库
- [ ] 开发侧边栏组件跟主视图组件

月底计划补充项：
输出崔sir的webpack视频

**Comment by qinshizhen** [comment]
## 重要事情
- [ ] 英语单词 90 + 30

## 学习
- [ ] 

## 工作
- [ ] 自动回复相关接口对接及调试

## 生活
- [ ] 俯卧撑 20
- [ ] 晚饭牛奶燕麦

**Comment by Song0129** [comment]
## 学习
  - [ ] 了解axios封装相关内容
  - [x] 整理工作业务逻辑

**Comment by suoutsky** [comment]
# 工作
1. [x] 需求提测配合跟进
2. [x]  首页部分弹窗由懒加载改为按需加载
3. [x] 技术方案评审
4. [x] 代码cr

# 学习
1. [x] 性能-三种懒加载和区别
2. [ ] [剑指 Offer 18. 删除链表的节点](https://leetcode-cn.com/problems/shan-chu-lian-biao-de-jie-dian-lcof/)
3. [ ] [环形链表](https://leetcode-cn.com/problems/linked-list-cycle/)
4. [ ] 计算属性：计算属性比普通函数好在哪里？
5. [ ] 侦听器：侦听器的实现原理和使用场景
6. [x] vue3中ref和reactive的区别
7. [x]  ReactiveFlags _v_skip 、__v_raw、__v_reactive 作用

# 生活&运动
1. [x] 打篮球
2. [x] 学会提问 看30分钟

# 思考🤔
1. [ ] 多弹层，复杂逻辑

**Comment by JackenJ** [comment]
![image](https://user-images.githubusercontent.com/77328954/148730905-fc3816fa-e51b-4b0d-a61c-352d5d0b34b2.png)

**Comment by J-django** [comment]
![image](https://user-images.githubusercontent.com/77328954/148730916-ac064a37-2855-44a4-a0d9-9c81f77dd7ca.png)

**Comment by FangzhouSu** [comment]
实习第一天 因为天津疫情原因 变成举家办公orz 不过leader给留了任务 学起来~
另外第一次学习打卡完成度比较低 今天开始算是day1吧！
day1
（下午四点才从北京折腾回天津 所以任务完成度可能略低？）
![image](https://user-images.githubusercontent.com/75036021/148733025-d148da02-8c29-4145-a105-945326581148.png)

**Comment by lingcha** [comment]
## 重要
- [ ] 阅读了不起的nodejs，尝试应用今天阅读的部分重构自己写的node应用
	- [x] static中间件
	- [x] query中间件
	- [x] logger中间件
	- [x] bodyparser中间件
	- [x] cookie
	- [x] session
	- [x] redis.cookie
	- [x] methodoverride中间件
	- [x] basicauth中间件 ????
### TypeScript
- [x] 阅读TypeScript官网的ObjectTypes
	- [x] Property Modifiers
	- [x] Optional Properties
	- [x] readonly Properties
	- [x] Index Signatures
	- [x] Extending Types
	- [x] Intersection Types
	- [x] intersection vs interface
#### 练习
- [ ] type-challenges练习3道，完成简单部分
	- [ ] Push
	- [ ] Unshift
	- [ ] Parameters

## 可选项
运用bootstrap5开发组件库
- [ ] 开发侧边栏组件跟主视图组件

## 月底计划补充项：
输出崔sir的webpack视频

**Comment by Irving2020** [comment]
![Screenshot_20220110_205610](https://user-images.githubusercontent.com/73822865/148769513-24caa501-4e17-4b81-abb0-2c148c713fe8.jpg)

**Comment by zhenyuWang** [comment]
### 昨天完成
leetcode-剑指 Offer 51-数组中的逆序对
[掘金](https://juejin.cn/post/7051431233091272734) [B站](https://www.bilibili.com/video/BV1RP4y1E7dw?spm_id_from=333.999.0.0)
面试题-闭包有什么应用场景？
### 今天要做
leetcode-1508-子数组和排序后的区间和
输出掘金 B站
面试题-闭包与函数柯里化、偏函数的关系？

**Comment by cherishing** [comment]
![image](https://user-images.githubusercontent.com/8589964/148867002-cfb0d133-81f9-414b-83c3-eb0369b07530.png)

**Comment by Irving2020** [comment]
![Screenshot_20220118_211242](https://user-images.githubusercontent.com/73822865/149944015-e57d17f2-7891-46fe-bdc1-11b2e42d02d0.jpg)
