### ISSUE TITLE
【每日计划】 2022-01-11

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#306]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/148861613-00239501-3937-43f0-b83d-6f6b75018948.png)

**Comment by Artsmp** [comment]
# 学习
- [x] 完成 promise 源码
- [ ] 完成 promise 相关的笔记 移到明日，用于复习
- [x] 结束高程4函数一章

# 工作
- [ ] xxxxx

# 日常
- [x] 每日护肤
- [x] 12:00 睡觉
- [x] 7:30 起床
- [x] 半小时看书
- [x] 午睡半小时

**Comment by fengjinlong** [comment]
#### 重要的事情 🍎

- [ ] minvue

#### 学习的事情 🧑‍💻

- [x] ts
- [ ] typing
- [x] 算法

#### 工地的事情 💤

- [x] ai bug

#### 生活的事情🍒

- [x] 休息

**Comment by Reinharclt** [comment]
![image](https://user-images.githubusercontent.com/35991053/148862570-f89bd8f0-64b5-4488-ae5f-893a70ee2827.png)

**Comment by qinshizhen** [comment]
## 重要事情
- [ ] 英语单词 90 + 30

## 学习
- [ ] 

## 工作
- [ ] 接口对接及调试

## 生活
- [ ] 俯卧撑 20
- [ ] 晚饭牛奶燕麦

**Comment by myltx** [comment]
![image](https://user-images.githubusercontent.com/29727848/148864539-17d1e2ac-1499-4fae-a1a4-09ae3acf49d5.png)

**Comment by luhaifeng666** [comment]
## 学习
- [x] 练习一道算法，并输出到git
- [x] 刷两篇技术帖子
## 生活
- [x] 铲屎

**Comment by bigfatDone** [comment]
![image](https://user-images.githubusercontent.com/41776522/148865402-3384a7c2-a737-49b2-90f1-b89020c94179.png)

**Comment by icodeish** [comment]
#### 重要的事
- [ ] vue项目练习
- [x] js面试题一道
- [x] vue面试题一道
- [ ] 红宝书第六章
- [ ] 犀牛书第六章
- [ ] leetcode每日一题

**Comment by Rainer-Yu** [comment]
## 今日 TODO💪
- [x] App分类封装
- [x] App点播/套餐课与分类页接口联调

## 学习🤯
- [ ] 整理JavaScript基础知识

## 生活🍹
- [ ] 拖地

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [ ] 《CSS 新世界》
- [x] 红宝书
- [x] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [x] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by REABLE-l** [comment]
## 每日计划 2022-01-11

### 学习
- [x] 英语高级语法
- [x] 绿宝书

### 生活
- [x] 铲屎 

### 读书
- [x] 《秘密》

**Comment by 1078269653** [comment]
## 重要
  - [x] 超过40分钟的运动
  - [x] 护肤
  - [x] 学习JavaScrip书籍一小时
  - [ ]  观看web前端教学视频三小时

**Comment by xiaoxiayan** [comment]
![image](https://user-images.githubusercontent.com/42376534/148868105-97005429-e2d5-47a0-a303-ff87ff4f180d.png)

**Comment by jp-liu** [comment]
![image](https://user-images.githubusercontent.com/79979500/148868132-515352c4-fc8c-447e-8a0a-b1111a5ddfa3.png)

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/148868536-a1ca14bb-0ca0-4841-b222-d5282b4d28c7.png)

**Comment by littlewhitehhh** [comment]
![image](https://user-images.githubusercontent.com/71918265/148868963-ff7e9f4a-bacb-4e7f-9c01-b9c0bbdae871.png)

**Comment by 999code** [comment]
- [x] 刷题5+道(今天的动态规划有点难度少来几道菜)
- [x] 复习动态规划专题
- [x] 追剧雪中

**Comment by ghost** [comment]
#### Task
- [x] 理解v-slot
- [x] 电商后台用户模块 修改、 分配角色

**Comment by CsongL** [comment]
![image](https://user-images.githubusercontent.com/30070610/148870763-a0eba099-77a7-45a6-8584-833270574ded.png)

**Comment by FangzhouSu** [comment]
【昨日复盘】[敲代码的小提琴手的学习日记](https://github.com/FangzhouSu/Constant-Front-End-Study/tree/main/Diary/%E6%A0%A1%E6%8B%9B%E5%B9%B4-2022-%E5%BF%B5%E5%BF%B5%E4%B8%8D%E5%BF%98%EF%BC%8C%E5%BF%85%E6%9C%89%E5%9B%9E%E5%93%8D/2022%E5%B9%B4%E5%AD%A6%E4%B9%A0%E6%97%A5%E6%8A%A5#110-%E5%BC%80%E5%A7%8B%E8%BF%9C%E7%A8%8B%E5%AE%9E%E4%B9%A0%E9%9B%86%E4%B8%AD%E7%B2%BE%E5%8A%9B%E5%85%A8%E5%8A%9B%E5%AD%A6%E4%B9%A0)
【今日学习】
群里滴朋友说得有道理 “菜就对了，大部分大佬都不水群orz” 🥺啪啪打脸 赶紧滚去学习辣！
实习第二天 不过明天才能办理远程入职 难过.jpg 
十点多才开始学习的一天😑 明天要早一些欸！那么 集中注意力 开始！
![image](https://user-images.githubusercontent.com/75036021/148871652-009ab92f-f344-4876-bc57-fc2785a76a26.png)

**Comment by J-django** [comment]
![image](https://user-images.githubusercontent.com/77328954/148872326-1982cd9b-fadc-450e-a62c-3a9f6e20c701.png)

**Comment by Song0129** [comment]
## 每日任务
- [ ] koa-setup学习、动手搭建
- [x] 看崔大的视频，学学小知识点

**Comment by Irving2020** [comment]
![image](https://user-images.githubusercontent.com/73822865/148873160-51f94a67-b4f3-4468-b310-d769e79d194b.png)

**Comment by suoutsky** [comment]
# 工作
1. [x] 需求提测配合跟进

# 学习
1. [x] 链表的基本结构
2. [ ] [剑指 Offer 18. 删除链表的节点](https://leetcode-cn.com/problems/shan-chu-lian-biao-de-jie-dian-lcof/)
3. [ ] [环形链表](https://leetcode-cn.com/problems/linked-list-cycle/)
4. [ ] 计算属性：计算属性比普通函数好在哪里？
5. [ ] 侦听器：侦听器的实现原理和使用场景

# 生活&运动
1. [x] switch健身游戏1小时
2. [x] 看30分钟书《学会提问》


# 思考🤔
1. [ ] 多弹层，复杂逻辑

**Comment by Vixcity** [comment]
# 2022-01-11日计划

2022-01-11日计划创建时间：2022-01-11 星期二  14:17
2022-01-11日计划创建人：Vixcity

## 重要的事
- [x] 别忘记给每日计划添加到目录里面去

## 学习
- [ ] 学习TS
- [x] 小程序

## 生活
- [ ] 1000天内容
- [ ] 手账

## 今日工作内容
- [x] 小程序

**Comment by cuixiaorui** [comment]
## 重要的事
- [ ] 录制 ts 类型体操


## 学习


## 生活
- [ ] 收拾屋子

**Comment by cggcbb** [comment]
### 【每日计划】 2022-01-11

#### 重要的事

- [ ] bug 修改. （未改完）

#### 学习

- [x] 搭建规范的 Vue3.x 项目工程环境。 参考 [从 0 开始手把手带你搭建一套规范的 Vue3.x 项目工程环境](https://juejin.cn/post/6951649464637636622)

#### 其他

- [x] 骑车半小时
 
 ###### 更新时间：2022-01-11 16:56:44

**Comment by runningOrange** [comment]
【每日计划】 2022-01-11
保证每天至少2小时学习时间
1.leetcode刷2道算法题    141. 环形链表   142. 环形链表 II
2.《你不知道的js》继续看this部分1个小时
3.健身40分钟
4.备考信息系统项目管理师复习1个小时

**Comment by zhenyuWang** [comment]
### 昨天完成
leetcode-1508-子数组和排序后的区间和
[掘金](https://juejin.cn/post/7051806710037479431) [B站](https://www.bilibili.com/video/BV1zP4y1E7gG?spm_id_from=333.999.0.0)
面试题-闭包与函数柯里化、偏函数的关系？
### 今天要做
leetcode-327-区间和的个数
输出掘金 B站
面试题-谈谈闭包与即时函数的应用？
