### ISSUE TITLE
【每日计划】 2022-01-12

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#307]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by ghost** [comment]
#### Task
电商后台管理
- [x] 分配权限
- [x] 权限列表
- [x] 商品列表
- [x] 将查询用户的功能构造一个新方法

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/149032381-a8895348-25f6-43bf-8f83-a47f0892935e.png)

**Comment by luhaifeng666** [comment]
## 学习
- [ ] 练习一道算法，并输出到git
- [x] 刷两篇技术帖子
## 生活
- [x] 铲屎

**Comment by fengjinlong** [comment]
#### 重要的事情 🍎

- [ ] minivue

#### 学习的事情 🧑‍💻

- [x] ts
- [ ] typing
- [x] issue

#### 工地的事情 💤

- [x] bug

#### 生活的事情🍒

- [x] 休息

**Comment by FangzhouSu** [comment]
【昨日复盘】[敲代码的小提琴手的学习日记](https://github.com/FangzhouSu/Constant-Front-End-Study/tree/main/Diary/%E6%A0%A1%E6%8B%9B%E5%B9%B4-2022-%E5%BF%B5%E5%BF%B5%E4%B8%8D%E5%BF%98%EF%BC%8C%E5%BF%85%E6%9C%89%E5%9B%9E%E5%93%8D/2022%E5%B9%B4%E5%AD%A6%E4%B9%A0%E6%97%A5%E6%8A%A5#111)
【今日学习】
day3 起得忒晚了orz 这要是在正常上班 就迟到了，，之后慢慢调作息了
![image](https://user-images.githubusercontent.com/75036021/149046202-610bb344-ae24-4416-954f-d7345aaf9514.png)

**Comment by Irving2020** [comment]
![image](https://user-images.githubusercontent.com/73822865/149046341-dc72e082-4f35-4d23-9d0b-70a536a39215.png)

**Comment by xiaoxiayan** [comment]
![image](https://user-images.githubusercontent.com/42376534/149046891-8ed6240d-0f57-4402-9183-17d335c6779b.png)

**Comment by runningOrange** [comment]
每日计划】 2022-01-12
保证每天至少2小时学习时间
昨日复盘：除了健身基本上都完成

今日计划：
1.leetcode刷2道算法题   202. 快乐数   206. 反转链表
2.《你不知道的js》继续看this部分1个小时
3.健身40分钟
4.备考信息系统项目管理师复习1个小时

**Comment by jp-liu** [comment]
![image](https://user-images.githubusercontent.com/79979500/149047943-9eda2f4c-6c86-42dd-8084-998f81d9ba8d.png)

**Comment by icodeish** [comment]
#### 重要的事
- [x] 完成移动端推广链接开发
- [ ] vue项目练习
- [ ] js面试题一道
- [ ] vue面试题一道
- [x] leetcode每日一题
- [ ] 红宝书第七章
- [ ] 犀牛书第七章

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [ ] 《CSS 新世界》
- [ ] 红宝书
- [ ] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [ ] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by REABLE-l** [comment]
## 每日计划 2022-01-12

### 提升
- [x] 英语高级语法
- [x] 绿宝书

### 生活
- [x] 约三五好友小酌一杯

### 锻炼
- [x] 打拳半小时

### 读书
- [x] 《秘密》

**Comment by myltx** [comment]
![image](https://user-images.githubusercontent.com/29727848/149049554-97499142-a7d2-4510-abe8-b8e5e7e1a65f.png)

**Comment by CsongL** [comment]
![image](https://user-images.githubusercontent.com/30070610/149049715-858254cc-be53-47e6-a4a1-05cd18f229ea.png)

**Comment by cherishing** [comment]
![image](https://user-images.githubusercontent.com/8589964/149049893-860986f6-3e5c-492b-bd22-d234b35a4d0c.png)

**Comment by Rainer-Yu** [comment]
## 今日 TODO💪
- [x] 年终总结
- [ ] 对接客服所需接口

## 学习🤯
- [x] 整理 `JS variable`

## 生活🍹
- [ ] 买菜&肉

**Comment by qinshizhen** [comment]
## 重要事情
- [ ] 英语单词 90 + 30

## 学习
- [ ] 

## 工作
- [ ] 接口对接及调试

## 生活
- [ ] 俯卧撑 20
- [ ] 晚饭牛奶燕麦
- [x] 公积金信息提交

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/149051700-667e7961-462f-4213-9733-ac1d0dc96ba6.png)

**Comment by fatFire** [comment]
## 每日任务
  - [x] leetcode 2道
  - [x] 优化项目

**Comment by Song0129** [comment]
## 每日任务

- [ ] 继续学习koa-setup
- [ ] 完成工作的任务

**Comment by cuixiaorui** [comment]
## 重要的事
- [ ] 实现 mini-vue 编译模块支持 element 元素的解析
- [ ] ts类型体操- readonly
- [ ] 建ts类型体操训练营（vx群）



## 学习
- [ ] [[学习高手]]
- [ ] [[零基础学好英语语法]]
- [ ] 自然拼读复习到 Pp #英语/自然拼读 


## 生活

**Comment by Artsmp** [comment]
# 学习
- [x] 总结函数式编程、JS 异步编程和手写 Promise
- [ ] 看高程4 promise 一章

# 工作
- [ ] xxxxx

# 日常
- [x] 每日护肤
- [x] 12:00 睡觉
- [ ] 7:00 起床
- [x] 半小时看书
- [x] 午睡半小时

**Comment by action-hong** [comment]
## 重要的事

- [ ] 产品测试
- [ ] Qman的ios相关兼容性问题解决

## 学习

- [ ] webpack相关知识点总结

**Comment by zzq1101921989** [comment]
### 工作
1. 修bug

### 生活
1. 学习一篇React相关技术文档
2. 学习React源码

**Comment by lixudong96** [comment]
# 2022-01-12
---
## 重要任务
```query
task-todo:"#task/vvip" path:day
```

## 微习惯
- [ ] typingclub #微习惯/打字练习
- [ ] 阅读两篇技术文章 #微习惯/阅读

## 今天要完成的工作 
- [ ] 完成后台系统路由的创建 #task/重要又紧急
- [ ] 通用表格 #task/重要不紧急
- [ ] 请求封装 #task/紧急不重要

## 日活事务
- [ ] 晚餐做可乐鸡翅
- [ ] 讨薪

---
																																								< [[{{date-1d:YYYY-NN-DD}} | 上一天]] | [[{{date+1d:YYYY-NN-DD}}| 后一天]] >

**Comment by 1078269653** [comment]
## 每日任务
  - [x] 护肤
  - [x] 超过40分钟的运动
  - [x] 学习web前端相关知识三小时

**Comment by zhenyuWang** [comment]
### 昨天完成
leetcode-327-区间和的个数
[掘金](https://juejin.cn/post/7052154137202393096) [B站](https://www.bilibili.com/video/BV1c34y1B7we?spm_id_from=333.999.0.0)
面试题-谈谈闭包与即时函数的应用？
### 今天要做
面试题-如何利用闭包完成类库封装？
leetcode-315-计算右侧小于当前元素的个数
leetcode-1302. 层数最深叶子节点的和
输出掘金 B站

**Comment by J-django** [comment]
![image](https://user-images.githubusercontent.com/77328954/149081712-45e1d70c-8700-4b4c-907c-99ea9aa4853f.png)

**Comment by 999code** [comment]
- [x] leetcode题7+
- [x] 三体有声剧2集
今日悟道：图和位运算需要加强

**Comment by Vixcity** [comment]
# 2022-01-12日计划

2022-01-12日计划创建时间：2022-01-12 星期三  10:10
2022-01-12日计划创建人：Vixcity

## 重要的事
- [x] 充饭卡
- [x] 别忘记给每日计划添加到目录里面去

## 学习
- [ ] 学习TS
- [ ] 研究一下TS的类型体操

## 生活
- [ ] 生活内容

## 今日工作内容
- [x] 小程序注册页面
