### ISSUE TITLE
【每日计划】 2022-01-13

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#309]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by ghost** [comment]
#### Task
电商后台管理
- [ ] 商品列表
- [ ] 分类参数
- [ ] 商品分类

**Comment by luhaifeng666** [comment]
## 学习
- [x] 练习一道算法，并输出到git
- [x] 刷两篇技术帖子
## 生活
- [x] 铲屎

**Comment by aifuxi** [comment]
![image](https://user-images.githubusercontent.com/65325004/149241540-2c392ae5-f661-49c3-94fd-47bf4aba12a9.png)
[每日计划](https://lenl2903ya.feishu.cn/docs/doccnFQ2C3r64e7XNce60YFyXSc)

**Comment by littlewhitehhh** [comment]
![image](https://user-images.githubusercontent.com/71918265/149243524-9a745512-0559-455c-9907-3b0e3fb02e3c.png)

**Comment by fengjinlong** [comment]
#### 重要的事情 🍎

- [x] minivue

#### 学习的事情 🧑‍💻

- [x] ts
- [x] 算法
- [x] typing
- [x] ob

#### 工地的事情 💤

- [x] 结束 ai

#### 生活的事情🍒

- [x] 休息

**Comment by Irving2020** [comment]
![image](https://user-images.githubusercontent.com/73822865/149248531-7b7a4fb0-7f63-4c7a-8a34-9678e1741cf0.png)

**Comment by pdsuwwz** [comment]
- [ ] 搭建项目基础框架

**Comment by icodeish** [comment]
#### 重要的事
- [x] 上班地铁牛客刷题十道
- [x] leetcode每日一题
- [ ] js面试题一道
- [ ] vue面试题一道
- [ ] github新建interviews 和leetcode库 并将之前总结的都提交
- [ ] 中午犀牛书第八章
- [ ] 下班地铁刷技术帖
- [ ] 到家做饭,饭后收拾休息半小时
- [ ] 练习项目
- [ ] 红宝书第八章

**Comment by REABLE-l** [comment]
## 每日计划 - 2022-01-13
### 提升
 - [x] 英语高级语法
 - [x] 绿宝书
 - [ ] 剑指offer

### 生活
 - [ ] *

### 锻炼
 - [ ] *

### 读书
 - [ ] 《一招制敌》

**Comment by lingmingchang** [comment]
- [ ] 复习一遍JS事件循环

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [x] 《CSS 新世界》
- [ ] 红宝书
- [x] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [ ] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by bigfatDone** [comment]
![image](https://user-images.githubusercontent.com/41776522/149251218-46745f1a-68e1-45ac-8b3e-159ba3e42008.png)

**Comment by myltx** [comment]
![image](https://user-images.githubusercontent.com/29727848/149251303-3773e3f3-1cb1-4f2c-a54b-cbe869815557.png)

**Comment by cherishing** [comment]
![image](https://user-images.githubusercontent.com/8589964/149252575-3543da90-a174-4c1a-8be8-10b9b9fdcde6.png)

**Comment by CsongL** [comment]
![image](https://user-images.githubusercontent.com/30070610/149252668-f26da80e-ed7b-42e2-befe-4b6b83980eb9.png)

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/149253264-3415978f-ac4b-4777-b945-439419687e90.png)

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/149253424-c650831e-4846-4a80-ba99-8c68ac3694e3.png)

**Comment by Song0129** [comment]
## 每日任务

- [ ] 总结koa-setup项目
- [ ] 完成工作内容

**Comment by jp-liu** [comment]
![image](https://user-images.githubusercontent.com/79979500/149253742-9720618d-1b91-4ab4-bdd1-5b07761d5a67.png)

**Comment by fatFire** [comment]
## 每日任务
  - [x] leetcode两道
  - [x] 整理项目
  - [x] js知识点学习

**Comment by Artsmp** [comment]
# 学习
- [ ] 用原生js实现日历功能
- [ ] 看vue官方文档

# 工作
- [ ] xxxxx

# 日常
- [ ] 每日护肤
- [ ] 12:00 睡觉
- [ ] 7:00 起床
- [ ] 半小时看书
- [ ] 午睡半小时

**Comment by qinshizhen** [comment]
## 重要事情
- [ ] 英语单词 90 + 30

## 学习
- [ ] 

## 工作
- [ ] 完成自定义菜单逻辑开发

## 生活
- [ ] 俯卧撑 20
- [ ] 晚饭牛奶燕麦

**Comment by cuixiaorui** [comment]
## 重要的事
- [ ] 探索 生成 element 的 children 代码的时候 vue3 是如何处理的
- [ ] 录制 ts类型体操- readonly



## 学习
- [ ] [[学习高手]]
- [ ] [[零基础学好英语语法]]
- [ ] 自然拼读Rr #英语/自然拼读 

## 生活

**Comment by 1078269653** [comment]
## 重要
  - [ ] 超过60分钟的运动
  - [ ] 护肤
  - [ ] 学习web前端教学视频三小时

**Comment by FangzhouSu** [comment]
【昨日复盘】[敲代码的小提琴手的学习日记](https://github.com/FangzhouSu/Constant-Front-End-Study/tree/main/Diary/%E6%A0%A1%E6%8B%9B%E5%B9%B4-2022-%E5%BF%B5%E5%BF%B5%E4%B8%8D%E5%BF%98%EF%BC%8C%E5%BF%85%E6%9C%89%E5%9B%9E%E5%93%8D/2022%E5%B9%B4%E5%AD%A6%E4%B9%A0%E6%97%A5%E6%8A%A5#112-%E5%88%9B%E5%BB%BA%E6%AF%8F%E6%97%A5%E4%B8%80%E9%A2%98%E4%BB%93%E5%BA%93-%E5%88%9B%E5%BB%BAself-introduction-profile-%E5%8A%A0%E5%85%A5uestc%E5%BC%80%E6%BA%90%E7%A4%BE%E5%8C%BA-%E5%BC%80%E5%90%AF%E6%97%A5%E6%9C%89%E6%89%80%E8%BF%9B%E4%B8%93%E5%8C%BA)

【今日规划】
![image](https://user-images.githubusercontent.com/75036021/149260883-b2dd302e-bf6d-44c3-a677-d8ac35498e4c.png)

**Comment by zhenyuWang** [comment]
### 昨天完成
面试题-如何利用闭包完成类库封装？
leetcode-315-计算右侧小于当前元素的个数
[掘金](https://juejin.cn/post/7052299208048508936) [B站](https://www.bilibili.com/video/BV1qZ4y1S7QM?spm_id_from=333.999.0.0)
leetcode-1302-层数最深叶子节点的和
[掘金](https://juejin.cn/post/7052254287316926477) [B站](https://www.bilibili.com/video/BV1UP4y1E7pn?spm_id_from=333.999.0.0)
### 今天要做
vue3.0源码课程1，2学习，并形成笔记
面试题-如何用闭包完成模块化(Webpack原理？

**Comment by 999code** [comment]
- [x] 找算法题
统计一个数字在排序数组中出现的次数。
员工 重要性
二叉树中和为某一值的路径
输入一棵二叉搜索树，将该二叉搜索树转换成一个排序的双向链表。要求不能创建任何新的结点，只能调整树中结点指针的指向。
给定一个二叉树和其中的一个结点，请找出中序遍历顺序的下一个结点并且返回。注意，树中的结点不仅包含左右子结点，同时包含指向父结点的指针。
- [x] 刷题5+
- [ ] 制定315面试冲刺计划
今日悟道：可能是因为年关了 最近几天状态不稳定 对近几天要学什么东西有点迷

**Comment by xiaoxiayan** [comment]
#  每日计划 2022-01-13

## 重要的事
- [x]  学习 obsidian 创建日记
- [x]  leetCode 二叉树
- [x]  bug



## 提升自己
- [ ]  keep
   


## 其他

**Comment by laddish** [comment]
# 2022-01-13_周四

## 重要的事
* [ ] 整理接口数据格式

 ## 学习
* [x] ts-challenge pick
* [x] 创建obsidian模版
* [x] 安装插件并提交到github

## 生活
* [x] 饿了么
* [x] 拼多多


## 代码片段
```typescript
type MyPick<T,K in keyof T> = {
	[P in K]:T[K]
}

//如何使用

interface User {

 name: string;

 age?: number;

 class?: string;

 sex: string;

}

  

type OnlyName = MyPick<User, "name">;

  

let a: OnlyName = { name: "a" };


```

**Comment by lwt09** [comment]
![image](https://user-images.githubusercontent.com/55039185/149289587-4791105a-6a70-4289-9b98-02f92623be4a.png)

**Comment by Vixcity** [comment]
# 2022-01-13日计划

2022-01-13日计划创建时间：2022-01-13 星期四  14:33
2022-01-13日计划创建人：Vixcity

## 重要的事
- [x] 别忘记给每日计划添加到目录里面去

## 学习
- [ ] 学习TS（未完成，晚上回去看看是否能完成）

## 生活
- [x] 抢26号车票

## 今日工作内容
- [x] 实现小程序首页、管理业、注册页宣传页UI图
