### ISSUE TITLE
【每日计划】 2022-01-17

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#313]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by wty9sky** [comment]
# 每日计划模板

## 学习
- [ ] leetcode1道题
- [ ] type-challanges项目创建与学习

## 生活
- [ ] 洗头发

## 工作
- [ ] 项目APP的Demo打包
- [ ] 完成接口文档
- [ ] 确定新项目排期计划
- [ ] 完成新项目设计稿

**Comment by zhenyuWang** [comment]
### 昨天完成
leetcode-56-合并区间
[B站](https://www.bilibili.com/video/BV1Ya411B7HX?spm_id_from=333.999.0.0)
leetcode-1288-删除被覆盖区间
[B站](https://www.bilibili.com/video/BV1g3411Y7Yw?spm_id_from=333.999.0.0)
面试题-为什么一定要有块级作用域？
### 今天要做
leetcode-491-递增子序列
leetcode-面试题 04.12-求和路径
输出B站

**Comment by Artsmp** [comment]
# 学习
- [ ] 学习 typescript 基础。尽量输出一些笔记
- [ ] 想要搭建 vue 组件库

# 工作
- [ ] 完成黄河bi项目列表数据对接

# 日常
- [ ] 每日护肤
- [ ] 12:00 睡觉
- [x] 7:00 起床
- [ ] 半小时看书
- [ ] 午睡半小时

**Comment by Reinharclt** [comment]
![image](https://user-images.githubusercontent.com/35991053/149686247-9de5ae6c-ebd0-4bca-8640-c48579f703d1.png)

**Comment by icodeish** [comment]
##  重要的事
- [ ] leetcode刷3道题
- [ ] js面试题一道
- [ ] vue面试题一道
- [ ] vue项目练习
- [ ] 犀牛书第九章
- [ ] 红宝书第十章

**Comment by xiaoxiayan** [comment]
#  每日计划 2022-01-17
---
## 重要的事
- [x]  leetCode
- [ ]  其他页面需求

---

## 提升自己
- [ ]  keep



---

## 其他

**Comment by Irving2020** [comment]
![image](https://user-images.githubusercontent.com/73822865/149687189-54d722b2-c2b0-4394-9802-37d73442c2a4.png)

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [ ] 红宝书
- [x] 阅读两篇技术文章

## 编码练习

- [ ] 复习JS手写题

## 其他

- [ ] 看面试八股文 

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by REABLE-l** [comment]
## 每日计划 - 2022-01-17
### 提升
 - [x] 英语高级语法
 - [x] 绿宝书
 - [ ] 剑指offer

### 生活
 - [ ] **

### 锻炼
 - [ ] **

### 读书
 - [ ] 《一招制敌》

**Comment by action-hong** [comment]
## 重要的事

- [ ] 跟进上周提测的两款产品(YBB, DB)
	- [x] YBB资料提测
	- [x] DB资料提测（等待签单预计明后天
- [x] 继续追TSD提供相关提测资料(反馈后天提供)
- [x] 年终总结PPT发给CJ过一遍
- [ ] YBB按摩椅插件修改，一次只能设置一个属性（设备限制导致
- [x] CCA的部署验证可行性
 
## 学习

- [x] 语义化背诵八股文，[[语义化]]
- [ ] 学习下less、scss/sass、stylus，区分对比

## 生活
- [ ] 下班回家拖地
- [ ] 洗衣服

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/149689487-fbde3bce-5bea-468f-910f-8caeddfe774a.png)

**Comment by cherishing** [comment]
![image](https://user-images.githubusercontent.com/8589964/149689549-8bb8f3a1-7a9e-4a58-9e73-a894ca3bbf3c.png)

**Comment by yekezz** [comment]
## 学习
- [ ] es6 两小时学习
- [ ] minivue

## 工作
- [ ] bug修复
- [ ] 测试
      

---- 来自vscode插件 "Study Plan"

**Comment by qinshizhen** [comment]
## 重要事情
- [ ] 英语单词 90 + 30

## 学习
- [ ] 

## 工作
- [ ] 公众号设置及人员设置 接口对接

## 生活
- [ ] 俯卧撑 20
- [ ] 牛奶燕麦

**Comment by Song0129** [comment]
## 每日任务

- [ ] koa-setup文章输出，做好相关总结
- [ ] 完成工作任务

**Comment by cuixiaorui** [comment]
## 重要的事
- [x] 剪视频 发b站
	- 加更 在公共场合下学习 （漏讲的一个点）
- [x] 打电话问问电脑 
- [x] mini-vue 补录 fix bug 视频



## 学习
- [ ] [[学习高手]]
- [ ] [[零基础学好英语语法]]
- [ ] 自然拼读Rr #英语/自然拼读 

## 生活
- [x] 买水

**Comment by ghost** [comment]
#### Task
电商后台管理
- [ ] 商品列表
- [ ] 商品参数

#### Preview
- [ ] Vuex
- [ ] Vim

#### Daily
- [ ] go to the bank

**Comment by luhaifeng666** [comment]
## 学习
- [ ] 练习一道算法，并输出到git
- [x] 刷两篇技术帖子
## 生活
- [x] 铲屎

**Comment by c0dedance** [comment]
# 2022-01-17

# 超级重要的事
  - [ ] 实验室新生考核方案

# 学习

  - [ ] 单词
  - [ ] 一题力扣算法题
  - [ ] java数据结构实现：双向链表
  - [x] 单测教程
  - [x] 阅读vue测试文档
  # 生活
   - [ ] 收拾行李

**Comment by fengjinlong** [comment]
#### 重要的事情 🍎

- [x] minivue

#### 学习的事情 🧑‍💻

- [x] ts
- [x] typing

#### 工地的事情 💤

- [ ] bug

#### 生活的事情🍒

- [x] 休息

**Comment by fatFire** [comment]
### 学习计划

- [ ] leetcode 两道
- [ ] 项目整理
- [ ] 面试学习

**Comment by lwt09** [comment]
![image](https://user-images.githubusercontent.com/55039185/149733754-d6221a45-dc8d-4ab6-8a84-ee068715b33b.png)

**Comment by Vixcity** [comment]
# 2022-01-17日计划

2022-01-17日计划创建时间：2022-01-17 星期一  09:13
2022-01-17日计划创建人：Vixcity

## 重要的事
- [x] 别忘记给每日计划添加到目录里面去

## 学习
- [ ] 学习TS
	
	小程序小知识：小程序如果想要在wxml里面传参，首先要用bindtap 绑定点击事件，在标签中利用 data-xxx  来定义你要传入的参数，然后事件中传入 event 用 event.currentTarget.dataset.xxx 来取你传入的值
	例如：
``` wxml
// wxml
<view data-whichType="{{item.whichType}}" bindtap="chooseWhichOne" ></view>
```

```js
chooseWhichOne(event){
	console.log(event.currentTarget.dataset)
}
```

## 生活
- [ ] 手账

## 今日工作内容
- [x] 小程序注册页面LOGO的UI
- [x] 小程序公共样式提炼
- [x] 小程序组件提炼
- [x] 小程序公共数据获取方式重构 => 提升速度
- [x] 小程序单个页面权限判断重构 => 提升速度
- [x] 小程序 => 订单管理 => 全部页面
- [x] 小程序 => 订单管理 => 待定价页面
- [x] 小程序 => 订单管理 => 生产中页面
- [x] 小程序 => 订单管理 => 已完成页面
- [x] 小程序管理界面图标添加
- [x] 小程序订单管理页面样式优化
- [x] 小程序数据统计下拉框
- [x] 小程序数据统计框架搭建完毕

**Comment by prefect-song** [comment]
## 学习
+ [x] 每日一题 
+ [x] 青训营课程
+ [x] 学习使用Obsidian进行每日任务的提交
+ [x] 整理CSS基础的笔记
+ [x] 青训营项目小组研讨会

**Comment by 999code** [comment]
- [x] 算法题5+
