### ISSUE TITLE
【每日计划】 2022-01-18

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#314]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by luhaifeng666** [comment]
## 学习
- [x] 练习一道算法，并输出到git
- [x] 刷两篇技术帖子
## 生活
- [x] 铲屎

**Comment by fengjinlong** [comment]
#### 重要的事情 🍎

- [x] minivue

#### 学习的事情 🧑‍💻

- [x] ts 闯关
- [x] ts 视频
- [x] typing

#### 工地的事情 💤

- [x] bug

#### 生活的事情🍒

- [x] 休息

**Comment by icodeish** [comment]
## 重要的事
- [x] 学习算法半小时
- [x] js面试题一道
- [x] vue面试题一道
- [ ] 打卡面试课
- [x] 犀牛书重读第十章
- [ ] 红宝书第十章

**Comment by fatFire** [comment]
## 学习计划

- [ ] leetcode 两道
- [ ] 项目整理
- [ ] 面试学习

**Comment by bigfatDone** [comment]
![image](https://user-images.githubusercontent.com/41776522/149855813-2b8cf3e1-b550-431c-8502-f5ea42987b12.png)

**Comment by myltx** [comment]
![image](https://user-images.githubusercontent.com/29727848/149855890-beecbc0c-2efd-43a6-8e7d-f5ebe16b2178.png)

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [ ] 《CSS 新世界》
- [ ] 红宝书
- [ ] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [ ] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by J-django** [comment]
![image](https://user-images.githubusercontent.com/77328954/149857050-53847faa-6eea-4309-ba44-0685bf42b741.png)

**Comment by action-hong** [comment]
## 重要的事

- [x] 学习下[What Is Amazon Kinesis Video Streams? - Amazon Kinesis Video Streams](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/what-is-kinesis-video.html)
	-  demo跑成功了但是控制台没有看到


## 学习

- [ ] 继续`less`,`scss`,`stylus`的区分
	- 只完成了变量的部分
- [x] `ts`体操写两题


## 生活

- [ ] 跑步
- [ ] 继续看《人生的智慧》

**Comment by qinran0423** [comment]
![截屏2022-01-18 上午10 00 49](https://user-images.githubusercontent.com/25677854/149857821-589f123e-9813-4f70-a8a6-9aad323f94de.png)

**Comment by yekezz** [comment]
## 学习
- [ ] es6 两小时学习
- [ ] minivue

## 工作
- [ ] bug修复
- [ ] 测试
      

---- 来自vscode插件 "Study Plan"

**Comment by CsongL** [comment]
![image](https://user-images.githubusercontent.com/30070610/149858084-8d5c0fe2-5402-4161-b284-cb6e4b58c708.png)

**Comment by cuixiaorui** [comment]
## 重要的事
- [ ] 备课 [[mini-vue]] 编译模块第一课
- [ ] 备课 类型体操 - firstArray 
- [ ] 整理任务清单


## 学习
- [ ] [[学习高手]]
- [ ] [[零基础学好英语语法]]
- [ ] 自然拼读Rr #英语/自然拼读 


## 生活
- [ ] 拿快递
- [ ] 信用卡

**Comment by xiaoxiayan** [comment]
#  每日计划 2022-01-18
---
## 重要的事
- [x]  leetCode
- [x]  css-content属性解决需求




## 提升自己
- [ ]  keep!!!!!
  



## 其他

**Comment by ghost** [comment]
#### Task
电商后台管理
- [ ] 添加商品

#### Preview
- [ ] Vuex
- [ ] Vim

**Comment by Song0129** [comment]
## 每日任务

- [ ] 实战VUE-SSR项目
- [ ] 完成工作内容

**Comment by prefect-song** [comment]
## 学习
+ [x] 每日一题 
+ [ ] 整理两篇笔记
+ [ ] 找到车牌检测的模型或数据集
+ [ ] 将框架跑通
## 生活 
+ [x] 打扫房子
+ [ ] 整理日记

**Comment by Artsmp** [comment]
# 学习
- [ ] 继续学习typescript高级类型

# 工作
- [ ] 小程序登录流程走通

# 日常
- [ ] 每日护肤
- [ ] 12:00 睡觉
- [ ] 7:00 起床
- [ ] 半小时看书
- [ ] 午睡半小时

**Comment by Vixcity** [comment]
# 2022-01-18日计划

2022-01-18日计划创建时间：2022-01-18 星期二  09:29
2022-01-18日计划创建人：Vixcity

## 重要的事
- [x] 别忘记给每日计划添加到目录里面去

## 学习
- [x] 学习TS

## 生活
- [x] 补上昨天落下的任务

## 今日工作内容
- [x] 小程序封装列表卡片
- [x] 小程序数据统计页面
- [x] 小程序客户管理页面
- [x] 小程序扫码时效问题解决
- [x] 小程序员工管理页面
- [x] 小程序封装列表卡片 - 完善
- [x] 修复订单管理样式Bug
- [x] 首页接口简单调通
- [x] 产量录入大体框架
- [x] 员工管理大体框架
- [x] tabbar页脚样式优化

**Comment by laddish** [comment]
# 2022-01-18_周二
## study-every-day
https://github.com/cuixiaorui/study-every-day/issues/

## 重要的事
* [x] 重构项目 
* [ ] bbb
* [ ] ccc

 ## 学习
* [x] tupleToObject
* [x] 复习readonly
* [x] 复习pick

## 生活
* [x] 饿了么
* [x] 拼多多


 ## 代码片段

 ### tupleToObject
 * 1.返回一个对象
 * 2.遍历数组 T[number]
 * keyof array => 索引
 * const let js世界 , type interface type世界 ,  两个平行世界
 * typeof 可以帮助我们把js世界的东西转化为ts类型世界

 ```typescript
type tupleToObject<T extends readonly (string|symbol|number)[]> = {
	[P in T[number]]:P
}
 ```

 ```javascript
function TupleToObject(array) {
	const obj = {}
	array.forEach(val => {
		obj[val] = val
	});
	return obj
}
 ```

 ```vue
 ```


### readonly
https://github.com/type-challenges/type-challenges/blob/master/questions/7-easy-readonly/README.md

给所有属性前面都加上 readonly
* 返回一个对象
* 遍历 obj 
	*  js 中是遍历对象
	*  ts 中是遍历接口
* 加上 readonly 关键字
* 通过 key 来获取 对象（ js ）/ 接口（ ts ）里面的值
```javascript
function readonly(obj){
	const result = {}
	for(const key in obj){
		result["readonly "+ key]: obj[key]
	}
	return result
}

```

* 使用 lookup 关键字 **keyof** 去拿到接口的所有值
* 需要遍历，用到知识点 mapped， 涉及关键字 **in**
* 加上关键字 **readonly**
* 通过 key 来获取接口里面的值  **indexed**

```typescript
type MyReadonly<T> = {
	readonly [P in keyof T]:T[P]
}
```

### pick

* extends关键字 用来约束 在不在一个类型中
* keyof关键字帮助我们获取到接口中所有的key

```typescript
type MyPick<T,K extends keyof T> = {
	[P in K]:T[P]
}
```

**Comment by zhenyuWang** [comment]
### 昨天完成
leetcode-491-递增子序列
[B站](https://www.bilibili.com/video/BV1a3411Y73a?spm_id_from=333.999.0.0)
leetcode-面试题 04.12-求和路径
[B站](https://www.bilibili.com/video/BV1US4y1571T?spm_id_from=333.999.0.0)
面试题-let是否会造成变量提升？
### 今天要做
输出文章-0.1+0.2 等于 0.3 吗？
面试题-介绍一下this指向4种形式
