### ISSUE TITLE
【每日计划】 2022-01-19

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#315]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by Artsmp** [comment]
# 学习
- [ ] 输出typescript笔记第一篇

# 工作
- [ ] 完成黄河小程序

# 日常
- [ ] 每日护肤
- [ ] 12:00 睡觉
- [ ] 7:00 起床
- [ ] 半小时看书
- [ ] 午睡半小时

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/150042662-bf3129bd-0eed-450b-a97a-aeac32558c9c.png)

**Comment by fengjinlong** [comment]
#### 重要的事情 🍎

- [ ] minivue

#### 学习的事情 🧑‍💻

- [ ] ts
- [ ] typing

#### 工地的事情 💤

- [ ] 可视化

#### 生活的事情🍒

- [ ] 休息

**Comment by myltx** [comment]
![image](https://user-images.githubusercontent.com/29727848/150045664-34608161-38a8-4e5f-bd6d-f4bd1bf0e4ce.png)

**Comment by action-hong** [comment]
## 重要的事

- [ ] ybb逻辑优化修改

## 学习

- [ ] 继续less相关
- [ ] ts体操两题


## 生活

- [ ] 看人生的智慧
- [ ] 医院

**Comment by xiaoxiayan** [comment]
#  每日计划 2022-01-19
---
## 重要的事
- [x]  leetCode 二叉树
- [ ]  输出一下文章
- [ ]  bug



## 提升自己
- [ ]  keep
  



## 其他

**Comment by J-django** [comment]
![image](https://user-images.githubusercontent.com/77328954/150046007-a9f2a2c8-4b54-426f-bbe7-a030e6589973.png)

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [x] 《CSS 新世界》
- [x] 红宝书
- [x] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [x] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by icodeish** [comment]
## 重要的事
- [x] 学习算法半小时
- [ ] js面试题一道
- [ ] vue面试一道
- [ ] 复盘面试课
- [ ] 博客框架选型、构思
- [ ] 犀牛书第八章
- [ ] 红宝书1-7章重读

**Comment by prefect-song** [comment]
## 学习
+ [x] 每日一题 
+ [ ] 整理框架
+ [ ] 跟导师开会
+ [ ] 做青训营课后作业
## 生活 
+ [ ] 葵请客吃饭，去芦台

**Comment by bigfatDone** [comment]
![image](https://user-images.githubusercontent.com/41776522/150048697-1a58914c-ceb6-4183-b8b1-fff5b24f09a4.png)

**Comment by CsongL** [comment]
![image](https://user-images.githubusercontent.com/30070610/150049094-81f79840-fd33-440c-b8d0-23a4c806b178.png)

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/150050060-ae86c5cf-c2cc-4380-8107-9f5e1421e266.png)

**Comment by fatFire** [comment]
# 每日计划

## 学习计划

- [ ] leetcode 两道
- [ ] 项目整理
- [ ] 面试学习

**Comment by suoutsky** [comment]
# 工作
1. [x] 请假

# 学习
1. [ ] vue2动态引入组件
2. [ ] [剑指 Offer 18. 删除链表的节点](https://leetcode-cn.com/problems/shan-chu-lian-biao-de-jie-dian-lcof/)
3. [ ] [环形链表](https://leetcode-cn.com/problems/linked-list-cycle/)
4. [ ] 计算属性：计算属性比普通函数好在哪里？
5. [ ] 侦听器：侦听器的实现原理和使用场景

# 生活&运动
1. [ ] 健身-胸
2. [ ] 看30分钟书《学会提问》- 价值观假设与描述性假设章节


# 思考🤔
1. [ ] 如何晚饭热量低且获得满足感？
2. [ ] 刷B站认知提升的视频

**Comment by laddish** [comment]
# 2022-01-19_周三
## 参考资料
### study-every-day
https://github.com/cuixiaorui/study-every-day/issues/

### type-challenges
https://github.com/type-challenges/type-challenges

### TypeScript: Documentation - The Basics
https://www.typescriptlang.org/docs/handbook/2/basic-types.html

## 重要的事
* [ ] 整理ts笔记
* [ ] bbb
* [ ] ccc

 ## 学习
* [x] https://github.com/type-challenges/type-challenges/tree/master/questions/14-easy-first
* [ ] bbb
* [ ] ccc

## 生活
* [x] 饿了么
* [ ] ccc

 ## 代码片段

## type First
 extends用作约束
 
 ### 疑问：never对应js中的什么？

 Some functions _never_ return a value:
 ```typescript
function fail(msg: string): never {
	
	throw new Error(msg);

} 
```
 The `never` type represents values which are _never_ observed. In a return type, this means that the function throws an exception or terminates execution of the program.

`never` also appears when TypeScript determines there’s nothing left in a union.
 有些函数永远不会返回一个值
 never类型代表着 永远不会被观察到的一个值
 在返回类型中 never代表着这个函数抛出一个错误 或程序结束运行了
 ```typescript
function fn(x: string | number) {
	
	if (typeof x === "string") {
	
	// do something
	
	} else if (typeof x === "number") {
	
	// do something else
	
	} else {
	
		x; // has type 'never'!
	
	}

}

 ```
 
### solution
 ```typescript
type First<T extends any[]> = T['length'] extends 0 ? never : T[0]
 ```

 ```javascript
 
 ```

 ```vue
 ```

**Comment by luhaifeng666** [comment]
## 学习
- [ ] 练习一道算法，并输出到git
- [ ] 刷两篇技术帖子
## 生活
- [x] 铲屎

**Comment by cuixiaorui** [comment]
## 重要的事
- [ ] 录制 - 类型体操 - firstArray 
- [ ] 备课 [[mini-vue]] 编译模块第一课
- [ ] 探索 cubox



## 学习
- [ ] [[学习高手]]
- [ ] [[零基础学好英语语法]]
- [ ] 自然拼读Ss  Tt


## 生活
- [ ] 洗

**Comment by cherishing** [comment]
![image](https://user-images.githubusercontent.com/8589964/150058414-6a71bd87-8057-4515-b317-5dfe732e2e8e.png)

**Comment by ghost** [comment]
#### Task
电商后台管理
- [ ] 添加商品
青训营
- [ ] 理解CSS
#### Preview
- [ ] Vuex
- [ ] Vim

**Comment by amebyte** [comment]
mini-vue学习

**Comment by 999code** [comment]
- [x] 力扣5+

**Comment by chenfan0** [comment]
![image](https://user-images.githubusercontent.com/83797583/150076927-dc746798-950d-4018-b403-cf8d278b2d6d.png)

**Comment by qinshizhen** [comment]
## 重要事情
- [x] 英语单词 90 + 30

## 学习
- [ ] 

## 工作
- [x] 资源库试卷库添加试题顺序
- [x] 自定义菜单接口对接

## 生活
- [x] 俯卧撑 20
- [x] 牛奶燕麦

**Comment by Irving2020** [comment]
![image](https://user-images.githubusercontent.com/73822865/150106639-1c2a429a-31cc-4019-8841-47b2ea08b9df.png)

**Comment by c0dedance** [comment]
# 2022-01-19

# 超级重要的事
  - [ ] 出考核题目(html/css)

# 学习

  - [ ] 单词
  - [ ] 一题力扣算法题
  - [ ] 学习崔大单测视频
  # 生活
 - [ ] 早睡

**Comment by zhenyuWang** [comment]
### 昨天完成
输出文章-0.1+0.2 等于 0.3 吗？
[掘金](https://juejin.cn/post/7056934829920616461)
面试题-介绍一下this指向4种形式
### 今天要做
leetcode-274-H 指数
leetcode-1122-数组的相对排序
输出B站
面试题-React中的事件绑定与箭头函数
