### ISSUE TITLE
【每日计划】 2022-01-20

### ISSUE THREAD

**Issue by yd160513** [cuixiaorui/study-every-day#316]

**Comment by icodeish** [comment]
## 重要的事
- [ ] 学习算法半小时
- [ ] js面试题一道
- [ ] vue面试题一道
- [ ] 完成网站首页背景动画
- [ ] 红宝书1-7章复读
- [ ] 犀牛书第7章复读

**Comment by qinshizhen** [comment]
## 重要事情
- [ ] 英语单词 90 + 30

## 学习
- [ ] 继续昨天学的学2节

## 工作
- [ ] 电商开发

## 生活
- [ ] 俯卧撑 20
- [ ] 牛奶燕麦
- [ ] 调研对比性价比***降噪耳机***
- [ ] 找班班咨询班

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/150246227-ccdb5f4a-35b1-406c-9c77-cdd812191dec.png)

**Comment by xiaoxiayan** [comment]
#  每日计划 2022-01-20
---
## 重要的事
- [x]  leetCode 二叉树
- [ ]  输出一道题的文章
- [x]  bug?



## 提升自己
- [ ]  keep
  



## 其他

**Comment by cuixiaorui** [comment]
## 重要的事
- [ ] 发布 - 类型体操 - firstArray 
- [ ] 备课 [[mini-vue]] 编译模块第一课
- [ ] 直播 - 唠嗑



## 学习
- [ ] [[学习高手]]
- [ ] [[零基础学好英语语法]]
- [ ] 自然拼读 Uu Vv


## 生活
- [ ] 洗

**Comment by myltx** [comment]
![image](https://user-images.githubusercontent.com/29727848/150247201-d004168a-ce50-42dc-b39d-6f19b2d10583.png)

**Comment by CsongL** [comment]
![image](https://user-images.githubusercontent.com/30070610/150247564-ce96ed10-f863-4935-bc67-90edd1e615ac.png)

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [ ] 《CSS 新世界》
- [ ] 红宝书
- [ ] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [ ] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by myltx** [comment]
![image](https://user-images.githubusercontent.com/29727848/150247201-d004168a-ce50-42dc-b39d-6f19b2d10583.png)

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/150254549-edfd853c-f7cf-419f-a3b5-babb3161cc40.png)

**Comment by fatFire** [comment]
# 每日计划

## 学习计划

- [ ] leetcode 两道
- [ ] 项目整理
- [ ] 面试学习

**Comment by ghost** [comment]
#### Task
- [ ] 图片上传
- [ ] 商品管理
- [ ] 代码调试课

#### Preview
- [ ] Vue2和Vue3的区别

**Comment by prefect-song** [comment]
## 学习
+ [x] 每日一题 
+ [ ] 青训营上课
+ [ ] 青训营作业
+ [ ] 一篇青训营笔记
+ [ ] 整理日记
+ [ ] 看一篇论文（或者半篇）

**Comment by 999code** [comment]
- [x] 力扣5+

**Comment by laddish** [comment]
# 2022-01-20_周四
## 参考资料
### study-every-day
https://github.com/cuixiaorui/study-every-day/issues/

### type-challenges
https://github.com/type-challenges/type-challenges

### TypeScript: Documentation - The Basics
https://www.typescriptlang.org/docs/handbook/2/basic-types.html

## 重要的事
* [ ] aaa
* [ ] bbb
* [ ] ccc

 ## 学习
* [x] 复习https://github.com/type-challenges/type-challenges/tree/master/questions/14-easy-first知识点
* [ ] bbb
* [ ] ccc

## 生活
* [x] 饿了么
* [ ] ccc

## 代码片段

### First of Array
#### 知识点

1. 如果是一个空数组的话 那么获取[0]是undefined
2. extends 的理解
```typescript
T extends [];

// 理解成

const arrStr = "[]"

console.log(
  arrStr === "[]"
)
```

#### 解法
1. 第一种方法 使用extends 写死


```typescript
type First<T extends any[]> = T extends [] ? never : T[0]

```

2. 第二种方法 获取 tuple 的 length 属性
```typescript
type First<T extends any[]> = T['length'] extends 0 ? never : T[0]

```

3. 第三种写法
T[number] 可以把数组里面的东西都遍历一遍 获取一个union类型
```typescript
type ages = [1, 2, 3];


// union 类型
// type t1 = 3 | 1 | 2
type t1 = ages[number];
```

1 extends 1 ; 1 extends 2； 1 extends 3

```typescript
[][number] // never
[never, never][number] // never

```


```typescript
type First<T extends any[]> = T[0] extends T[number] ? T[0] : never

```

4. 第四种做法

inter(推断) 的使用 推断

看看能不能解构出来一个 first 如果能解构就返回出去  如果没有就是一个 never

通过 infer 去解构一个数组 和 js 中去解构一个数组是一样的 写法

 ```typescript
type First<T extends any[]> = T extends [infer First, ...infer Rest] ? First : never;

type Rest<T extends any[]> = T extends [infer First, ...infer Rest] ? Rest : never;
 ```

 ```javascript
 
 ```

 ```vue
 ```

**Comment by XUBXUE** [comment]
## 每日任务
  - [x] 阅读学习Vue3、Vite官方文档
  - [x] 阅读红宝书BOM章节
  - [ ] B站观看Vue3源码解析

**Comment by wenzheng-yi** [comment]
必须完成的任务：输出《从软件设计看页面编写》文章

**Comment by luhaifeng666** [comment]
## 学习
- [x] 练习一道算法，并输出到git
- [x] 刷两篇技术帖子
## 生活
- [x] 铲屎

**Comment by fengjinlong** [comment]
#### 重要的事情 🍎

- [x] minivue

#### 学习的事情 🧑‍💻

- [ ] ts
- [x] typing

#### 工地的事情 💤

- [x] 可视化

#### 生活的事情🍒

- [x] 休息

**Comment by Vixcity** [comment]
# 2022-01-20日计划

2022-01-20日计划创建时间：2022-01-20 星期四  14:25
2022-01-20日计划创建人：Vixcity

## 重要的事
- [x] 别忘记给每日计划添加到目录里面去

## 学习
- [ ] 学习TS

## 生活
今天发工资
今天老板说过年送是羊毛衫
- [ ] 拿快递


## 今日工作内容
- [x] 小程序-订单管理-生产定价和生产进度
- [x] 小程序产量尺码颜色录入
- [x] 首页懒加载Bug修复
- [x] 小程序产量自由录入
- [x] 自由录入递归补齐算法
- [x] 数据统计接口调通

**Comment by action-hong** [comment]
## 重要的事

- [ ] YBB今天会寄板子过来，验证
- [x] 年终述职
- [x] YFD的app输出，中午发一个版本
- [x] QMAN的app最终版输出
- [ ] YBB的提测材料重新提交（安排周五测试

## 学习

- [ ] 继续less和scss
- [x] es2021相关语法归纳
- [x] ts体操两题

## 生活

- [ ] 读书《人生的智慧》

**Comment by zhenyuWang** [comment]
### 昨天完成
leetcode-274-H 指数
[B站](https://www.bilibili.com/video/BV1tF411n7cL?spm_id_from=333.999.0.0)
leetcode-1122-数组的相对排序
[B站](https://www.bilibili.com/video/BV1tR4y1u7LF?spm_id_from=333.999.0.0)
面试题-React中的事件绑定与箭头函数
### 今天要做
拓扑排序
输出掘金 B站
面试题-手写 call、apply、bind
