### ISSUE TITLE
【每日计划】 2022-01-21

### ISSUE THREAD

**Issue by yd160513** [cuixiaorui/study-every-day#318]

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/150445963-f07b1071-e110-47f3-9bac-20cba742f993.png)

**Comment by Artsmp** [comment]
# 学习
- [ ] 看typescript书籍
- [ ] 看css书籍

# 工作
- [ ] 完成酒店云前端页面

# 日常
- [ ] 每日护肤
- [ ] 12:00 睡觉
- [ ] 7:00 起床
- [ ] 半小时看书
- [ ] 午睡半小时

**Comment by cuixiaorui** [comment]
## 重要的事
- [ ] 每日计划的 issue 创建失败
- [ ] 备课 [[mini-vue]] 编译模块第一课



## 学习
- [ ] [[零基础学好英语语法]]
- [ ] 自然拼读 Uu Vv
- [ ] 《好好学习-个人知识管理精进指南》


## 生活
- [ ] 洗

**Comment by xiaoxiayan** [comment]
#  每日计划 2022-01-21
---
## 重要的事
- [x]  leetCode




## 提升自己
- [ ]  keep
  



## 其他

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [ ] 《CSS 新世界》
- [ ] 红宝书
- [ ] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [ ] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by qinshizhen** [comment]
## 重要事情
- [ ] 英语单词 90 + 30

## 学习
- [ ] 继续昨天学的学2节
- [ ] 争取看一节面试

## 工作
- [ ] 电商PC端继续开发
- [ ] 结尾自动回复、自定义菜单

## 生活
- [ ] 俯卧撑 20
- [ ] 牛奶燕麦
- [ ] 京东快递： 健力宝、拖鞋、耳机

**Comment by bigfatDone** [comment]
![image](https://user-images.githubusercontent.com/41776522/150449552-3831d5d1-4341-47b1-82ef-14d11fc54ca8.png)

**Comment by FangzhouSu** [comment]
跟校友的打卡计划失败 没人一起orz 我又回来了
![image](https://user-images.githubusercontent.com/75036021/150449811-4d746126-48d4-4660-99f3-6cdce6893cd7.png)

**Comment by myltx** [comment]
![image](https://user-images.githubusercontent.com/29727848/150450494-8b577141-b6b4-42fc-b6c8-a86da16bf211.png)

**Comment by icodeish** [comment]
## daily plan
- [ ] 学习算法半小时
- [ ] js面试题一道
- [ ] vue面试题一道
- [ ] 研究下vitepress

**Comment by XUBXUE** [comment]
## 学习
  - [ ] 阅读学习Vue3、Vite官方文档
  - [x] 阅读红宝书BOM章节
## 工作
  - [ ] 用vue3重构领导给的老系统项目

**Comment by cherishing** [comment]
![image](https://user-images.githubusercontent.com/8589964/150452742-bb374f10-e7c0-4f1e-8dd8-d77318ae3e82.png)

**Comment by fatFire** [comment]
# 每日计划

## 学习计划

- [ ] leetcode 两道
- [ ] 项目整理
- [ ] 面试学习

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/150453296-2c6758c6-c056-4f78-94cc-aa7f67f36948.png)

**Comment by luhaifeng666** [comment]
# 工作
- [ ] 菜单优化

# 学习
- [ ] 练习一道算法，输出到git
- [ ] 刷两篇技术贴

# 生活
- [x] 铲屎

**Comment by ghost** [comment]
#### Task
- [ ] 图片上传
- [ ] 商品管理
- [ ] 代码调试课

#### Preview
- [ ] Vue2和Vue3的区别

**Comment by Blacktuna1** [comment]
- 下午（2-6）4h
- [x] 泡杯咖啡
- [ ] 逛逛谷歌地球（1h
- [x] html五节（1h
- [ ] 日语一课（1h
- [ ] 力扣两道题
- 晚上
- [ ] 不出去
- [ ] 看会儿书

**Comment by fengjinlong** [comment]
#### 重要的事情 🍎

- [x] minivue

#### 学习的事情 🧑‍💻

- [ ] ts
- [x] typing

#### 工地的事情 💤

- [x] 可视化

#### 生活的事情🍒

- [x] 休息

**Comment by Vixcity** [comment]
# 2022-01-21日计划

2022-01-21日计划创建时间：2022-01-21 星期五  09:48
2022-01-21日计划创建人：Vixcity

## 重要的事
- [x] 别忘记给每日计划添加到目录里面去

## 学习
- [ ] 学习TS

## 生活

## 今日工作内容
- [x] 数据统计页面数据渲染
- [x] 录入时候进行过滤补充到提交函数里面
- [x] 历任作坊离职结构修改
- [x] 重复申请提示
- [x] 员工管理接口调用
- [x] 员工管理页面完
- [x] 数据统计作坊主版
- [x] 订单管理tab切换
- [x] 产量录入作坊主版
- [x] orderCard进行切换code和title
- [x] 首页和产量录入orderCard数据重构
- [x] 订单管理和订单详情orderCard数据重构
- [x] 首页样式Bug修复

**Comment by prefect-song** [comment]
## 学习
+ [x] 每日一题 
+ [x] 青训营课程
+ [x] 青训营作业
+ [x] 整理两篇笔记
## 生活 
+ [x] 整理日记
+ [x] 洗头

**Comment by 999code** [comment]
- [x] 读算法4  1.1
- [x] 做题2+

**Comment by zhenyuWang** [comment]
### 昨天完成
拓扑排序
[掘金](https://juejin.cn/post/7024096823937597448) [B站](https://www.bilibili.com/video/BV1VY41187ti?spm_id_from=333.999.0.0)
面试题-手写 call、apply、bind
### 今天要做
leetcode-207-课程表
leetcode-210-课程表 II
输出掘金 B站
面试题-介绍一下this指向 4 种形式？
