### ISSUE TITLE
【每日计划】 2022-01-23

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#321]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [x] 《CSS 新世界》
- [x] 红宝书
- [x] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [ ] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by cuixiaorui** [comment]
## 重要的事
- [ ] 录制 如何学习 ts
- [ ] 更新 mini-vue 的 readme



## 学习
- [ ] 阅读周刊
- [ ] 《好好学习-个人知识管理精进指南》
- [x] [[零基础学好英语语法]]
- [x] 自然拼读 Aa


## 生活

**Comment by fatFire** [comment]
# 每日计划

## 学习计划

- [ ] leetcode 两道
- [ ] 项目整理
- [ ] 面试学习

**Comment by xiaoxiayan** [comment]
#  每日计划 2022-01-23
---
## 重要的事
- [ ]  leetCode 二叉树
- [ ]  输出这道题



## 提升自己
- [ ]  keep
  



## 其他

**Comment by ghost** [comment]
#### Task
- [ ] 商品管理

#### Preview
- [x] Vue3

**Comment by leop001** [comment]
# 学习

- [ ] oj平台教师端基本框框
- [ ] vue3基础视频

**Comment by 999code** [comment]
- [x] 力扣6+

**Comment by c0dedance** [comment]
# 2022-01-23

# 超级重要的事
  - [x] 补全单测文件

# 学习

  - [x] 单词
  - [x] 一题力扣算法题
  - [ ] 等
  # 生活

**Comment by Vixcity** [comment]
# 2022-01-23日计划

2022-01-23日计划创建时间：2022-01-23 星期日  09:32
2022-01-23日计划创建人：Vixcity

## 重要的事
- [x] 别忘记给每日计划添加到目录里面去

## 学习
- [x] 学习TS

## 生活
- [x] 写周复盘[[周复盘-2022年第03周]]
- [ ] 内容输出

状态：心力交瘁

## 今日工作内容
- [x] 小程序扫描普通二维码跳转进小程序
- [x] 绑定工厂
- [ ] 绑定订单

**Comment by zhenyuWang** [comment]
### 昨天完成
基数排序
[掘金](https://juejin.cn/post/7024096823937597448) [B站](https://www.bilibili.com/video/BV1LT4y1y7Kg?spm_id_from=333.999.0.0)
leetcode-164-最大间距
[B站](https://www.bilibili.com/video/BV153411h7mk?spm_id_from=333.999.0.0)
面试题-呈现一个wiki页面你会用到哪些语义化标签?
### 今天要做
leetcode-763-划分字母区间
输出B站
面试题- window 对象除 document 以外的还有什么子对象？
