### ISSUE TITLE
【每日计划】 2022-02-18

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/study-every-day#353]
[如何写每日任务](https://github.com/cuixiaorui/study-every-day/blob/main/sed/daily-task.md)

**Comment by WalkerChan2019** [comment]
### 昨日总结
1. 工作：移交大屏项目给同事，完全切换到lhz项目；安装安卓SDK，有坑.....
2. 阅读vue-cli-serve源码和webpack文档

### 今日计划
- 完成安卓端打包并测试

**Comment by yd160513** [comment]
![image](https://user-images.githubusercontent.com/34637837/154596203-3c524c4d-097b-496c-8747-e2df70649dcc.png)

**Comment by Vixcity** [comment]
# 2022-02-18日计划

2022-02-18日计划创建时间：2022-02-18 星期五  09:06
2022-02-18日计划创建人：Vixcity

## 重要的事
- [x] 别忘记给每日计划添加到目录里面去

## 学习
- [ ] 摄影
- [ ] 吉他

## 生活

## 今日工作内容
- [x] 员工账号下，也可看到客户管理、订单管理、客户管理功能 bug 修复
- [x] 员工身份下，只能看到自己账号历史所有的数据统计 bug 修复
- [x] 员工（王寒）录入产量后，在数据统计里看不到 bug 修复
- [x] 员工（王寒）身份下，不可在首页点击切换产品名/产品编号 bug 修复
- [x] 员工录入产量后提示成功，但是（作坊主查看）数据统计里显示人员为作坊主 bug 修复
- [x] 作坊主已定价，员工查看产品订单依旧没显示单价 bug 修复

**Comment by littlewhitehhh** [comment]
![image](https://user-images.githubusercontent.com/71918265/154598086-87b7e707-f0c5-49d1-848b-3c0b5e30d466.png)

**Comment by ghost** [comment]
#### Task
项目
- [ ] 热门搜索
- [ ] 点赞
- [ ] VIP专区
- [ ] 动态

#### Preview
- [ ] 基础面试题10道

**Comment by fengjinlong** [comment]
#### 重要的事情 🍎

- [x] 清空
- [x] 预览保存
- [x] 尺寸

#### 学习的事情 🧑‍💻

- [ ] 看书
- [ ] 题库

#### 工地的事情 💤

- [x] 

#### 生活的事情🍒

- [x] 休息

**Comment by ch3cknull** [comment]
# 每日计划模板

## 读书

- [ ] 《CSS 新世界》
- [ ] 红宝书
- [ ] 阅读两篇技术文章

## 编码练习

- [ ] mini-vue
- [ ] 练习 TypeScript

(该模板使用[ch3cknull/auto-issue-comment](https://github.com/ch3cknull/auto-issue-comment)自动生成)

**Comment by cherishing** [comment]
![image](https://user-images.githubusercontent.com/8589964/154601837-bc0242d7-1a9a-44c9-9ef1-9e75cc30a43f.png)

**Comment by bigfatDone** [comment]
![image](https://user-images.githubusercontent.com/41776522/154604446-c4311ee8-f1b9-4bdf-a838-66ccae9ad239.png)

**Comment by cuixiaorui** [comment]
## 重要的事
- [ ] 备课 mini-vue 新的一集
- [ ] 发pyq


## 学习
- [ ] [[零基础学好英语语法]]
- [ ] 阅读 Vuejs - 第一章
- [ ] 读书 - 自我营销
- [ ] 自然拼读 Uu


## 生活
- [ ] 收拾屋子

**Comment by lingcha** [comment]
- Webpack
- [ ] 使用webpack-dev-server
- [ ] 热模块替换
- [ ] webpack融合babel进行es6转es5 
- [ ] 代码分离 splitChunksPlugin

- Vue Test Utils - 要点，基本
- [ ] 概览Getting Started
- [ ] 阅读并完成A Crash Course
- [ ] 阅读并完成Conditional Rendering


# 阅读材料
- [x] git flow 工作流 翻译到typora


# 工作准备
- [x] 阅读邮件准备工作

**Comment by supermanklk** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/28639384/154607303-a6b69552-174e-4779-ae69-0ed4b2d68a75.png">

**Comment by qinran0423** [comment]
![image](https://user-images.githubusercontent.com/25677854/154610041-aa1afb81-98bd-4dbf-b10e-39224f8346b9.png)

**Comment by qinshizhen** [comment]
## 重要事情
- [ ] 英语单词干

## 学习
- [x] 一篇面试掘金
- [x] 开小课两门课

## 工作
- [x] 教学账套初始化功能添加
- [x] 真实电商 代码合并 部署

## 生活
- [ ] 俯卧撑 20
- [ ] 给哥们过生日，吃肉

**Comment by icodeish** [comment]
## daily_plan
- [ ] leetcode刷题5道

**Comment by luhaifeng666** [comment]
- [x] 练习一道算法，输出到git
- [x] 刷两篇技术贴

**Comment by zhenyuWang** [comment]
### 昨天完成
Vue3源码课程学习
面试题-Promise与有限状态机的关系
### 今天要做
Vue3源码课程学习
面试题-Generator 如何解决回调地狱
